Use separate jobs instead of child_process (#881)
Co-authored-by: amvanbaren <aart.vanbaren@eclipse-foundation.org>

diff --git a/.github/workflows/publish-extensions.yml b/.github/workflows/publish-extensions.yml
--- a/.github/workflows/publish-extensions.yml
+++ b/.github/workflows/publish-extensions.yml
@@ -29,67 +29,75 @@ jobs:
       FORCE: ${{ github.event.inputs.forcefullyPublish }}
     name: Publish Extensions
     runs-on: ubuntu-latest
+    permissions:
+      actions: write
+      contents: read
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4.3.0
         with:
           node-version: "20.x"
-      - uses: oven-sh/setup-bun@v2
-        with:
-          bun-version: latest
-      - name: Set up pyenv
-        uses: "gabrielfalcao/pyenv-action@32ef4d2c861170ce17ded56d10329d83f4c8f797"
-        with:
-            command: python --version
-      - name: Set default global version
-        run: |
-          pyenv install 3.8
-          pyenv global 3.8
-      - uses: actions/setup-java@v4
-        with:
-          distribution: "microsoft"
-          java-version: "21"
-      - name: Install dependencies for native modules
-        run: |
-          sudo apt-get update
-          sudo apt-get install libpango1.0-dev libgif-dev
       - run: npm install
       - run: npm i -g @vscode/vsce pnpm
-      - run: node publish-extensions
+      - uses: actions/github-script@v7
         env:
-          OVSX_PAT: ${{ secrets.OVSX_PAT }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Report results
-        run: bun run ./report-extensions.ts
-      - uses: actions/upload-artifact@v4
-        if: always()
+          REPOSITORY: ${{ github.repository }}
         with:
-          name: report
-          path: |
-            /tmp/stat.json
-            /tmp/result.md
-      - uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: artifacts
-          path: |
-            /tmp/artifacts/*.vsix
-      - name: Upload job summary
-        if: always()
-        run: cat /tmp/result.md >> $GITHUB_STEP_SUMMARY
-      - name: Get previous job's status
-        id: lastrun
-        uses: filiptronicek/get-last-job-status@main
-      - name: Slack Notification
-        if: ${{ !github.event.inputs.extensions && ((success() && steps.lastrun.outputs.status == 'failed') || failure()) }}
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_WEBHOOK: ${{ secrets.GITPOD_SLACK_WEBHOOK }}
-          SLACK_COLOR: ${{ job.status }}
+          script: |
+            const script = require('./scripts/publish-extensions.js');
+            await script(async (extension, context) => {
+              const [owner, repo] = process.env.REPOSITORY.split("/");
+              await github.request("POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches", {
+                  owner,
+                  repo,
+                  workflow_id: "publish-extension.yml",
+                  ref: "build-extension",
+                  inputs: {
+                      extension: JSON.stringify(extension),
+                      publishContext: JSON.stringify(context),
+                      force: process.env.FORCE,
+                      skipPublish: process.env.SKIP_PUBLISH,
+                  },
+                  headers: {
+                      "X-GitHub-Api-Version": "2022-11-28",
+                  },
+              });
+            });
+      # TODO fix reporting
+      # - name: Report results
+      #   run: bun run ./report-extensions.ts
+      # - uses: actions/upload-artifact@v4
+      #   if: always()
+      #   with:
+      #     name: report
+      #     path: |
+      #       /tmp/stat.json
+      #       /tmp/result.md
+      # - uses: actions/upload-artifact@v4
+      #   if: always()
+      #   with:
+      #     name: artifacts
+      #     path: |
+      #       /tmp/artifacts/*.vsix
+      # - name: Upload job summary
+      #   if: always()
+      #   run: cat /tmp/result.md >> $GITHUB_STEP_SUMMARY
+      # - name: Get previous job's status
+      #   id: lastrun
+      #   uses: filiptronicek/get-last-job-status@main
+      # - name: Slack Notification
+      #   if: ${{ !github.event.inputs.extensions && ((success() && steps.lastrun.outputs.status == 'failed') || failure()) }}
+      #   uses: rtCamp/action-slack-notify@v2
+      #   env:
+      #     SLACK_WEBHOOK: ${{ secrets.GITPOD_SLACK_WEBHOOK }}
+      #     SLACK_COLOR: ${{ job.status }}
   check_parity:
     name: Check MS parity
     runs-on: ubuntu-latest
     needs: publish_extensions
+    permissions:
+      actions: none
     if: ${{ !github.event.inputs.extensions }} # only run on full runs
     steps:
       - uses: actions/checkout@v4
